### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by iKeyToLife** [bryan-mcintyre/Pokemon-Battle-V2#4]
# Items
## Please describe your suggestions for subjects. the points are as follows
1. Item name
2. Description of the item
3. What should you do (heal, buff, debuff, increase any parameters, etc.)
4. Exactly how it should work. For example, a health bottle restores 50 health units.
lightning scroll, deals 20 damage to the enemy and reduces armor by 30%.

**Comment by LeenaCruz** [comment]
Ideas for Healing Items: 
 **Regular Potion**
A spray-type medicine for treating wounds. 
Heal
It restores the HP of one Pokémon by 20 points.

**Hyper Potion** 
A spray-type medicine for treating wounds. 
Heal
It restores the HP of one Pokémon by 200 points.

**Max Potion**
A spray-type medicine for treating wounds.
Heal 
It will completely restore the max HP of a single Pokémon.

**Revive** 
A medicine that can revive fainted Pokémon. 
 Revive 
It also fully restores half of a fainted Pokémon's maximum HP (so restores 50%).

**Max Revive**
A medicine that can revive fainted Pokémon.
Revive
It also fully restores a fainted Pokémon's maximum HP.

**Comment by iKeyToLife** [comment]
great work
