### ISSUE TITLE
Ability

### ISSUE THREAD

**Issue by iKeyToLife** [bryan-mcintyre/Pokemon-Battle-V2#5]
# Ability for pokemons
## Please describe your suggestions for subjects. the points are as follows
1. Ability name
2. Description of the ability
3. What should you do (heal, buff, debuff, increase any parameters, etc.)
### 4. Exactly how it should work. For example:
```
increase your damage by 20 units.
Or as a percentage of 30%.

Reduces enemy armor by 20 units 
Or a percentage of 30%.

Increased speed, etc.
```

**Comment by LeenaCruz** [comment]
**Battle Armor**
The Pokémon is protected against critical hits.
Buff
Protected against critical hits (let's say attacks over 50-80 power) in the next 3 rounds.

**Berserk**
Raises attack when HP drops below half.
Buff
It increases attack power 200% when HP drops below half.

**Comment by iKeyToLife** [comment]
we add in future
